### ISSUE TITLE
writing signature and Certificate Error

### ISSUE THREAD

**Issue by eymengunay** [eymengunay/php-passbook#19]
This error was initially reported in [PassbookBundle](https://github.com/eymengunay/PassbookBundle) by @Numerah. Moving it here as the bug is caused by this library.

https://github.com/eymengunay/PassbookBundle/issues/3

>i have generated the passbook application and when i generate passes they are working on every possible device (android ,mac) but IOS 7 iphones and above
when i check iPhone utility manager it was giving me this error: Invalid data error reading pass: The passTypeIdentifier or teamIdentifier provided may not match your certificate, or the certificate trust chain could not be verified. i have my generated certificates and i have seen green sign on the certificates and in my key chain access they are mentioned as verified certificates. there must be a mistake in writing signature or else kindly put some light on this error

**Comment by g-** [comment]
In my experience, a pass must have an icon image in order to be valid, but it does not require an icon@2x image.
