### ISSUE TITLE
Coupon type passes must show secondary and auxiliary fields in one row?

### ISSUE THREAD

**Issue by Numerah** [eymengunay/php-passbook#20]
in any other type it is ok to show secondary and auxiliary fields in different rows but in coupon type 2 secondary and 2 auxiliary must be allowed which i implemented already. but they are showing in different rows just like every other type of pass. they must list in one row like this
![secondaryauxiliary](https://cloud.githubusercontent.com/assets/4244577/2752784/219cd306-c91e-11e3-8f20-f62f25272b9f.png)

**Comment by g-** [comment]
The pass does not define the layout of the rows, only the content of the fields. The layout is generated by the Wallet (Passbook) application and may vary depending on the iOS version and/or device.
