### ISSUE TITLE
Possible problem with NumberField generation using CurrencyCode

### ISSUE THREAD

**Issue by ellorensc** [eymengunay/php-passbook#27]
We have noticed that generating a StoreCard using NumberField to inform the amount does not show anything if you set the curredncy code (NumberField::setCurrencyCode())

In order to solving this issue we had to override this function forcing an integer casting return:

/**
     * @return int
     */
    public function getValue()
    {
        return (int)parent::getValue();
    }

**Comment by g-** [comment]
Setting the value as a number (int or float) rather than a string will fix this problem. Casting to an int won't work for numeric values that are not integers.
