### ISSUE TITLE
Associated Store Identifiers

### ISSUE THREAD

**Issue by FuLLn00b** [eymengunay/php-passbook#28]
I have not managed to use correctly the 'associatedStoreIdentifiers' attribute of the Pass class with current version of the code.
I used this line of code: 
$pass->addAssociatedStoreIdentifier(585027354);
The number 85027354 is the adam id of Google Maps.
Thing is that this attribute is not in the list of properties in the toArray() function of the same class, so when the pkpass is created, the associatedStoreIdentifers aren't in the JSON of the pass.

I added two lines in the toArray() function to make it work: after the foreach, i added:
if(count($this->associatedStoreIdentifiers) != 0)
            $array['associatedStoreIdentifiers'] = $this->associatedStoreIdentifiers;
And now it works perfectly, i see the GoogleMaps link at the back of the pass.

Not sure if i'm doing it wrong or if there is an issue.

**Comment by g-** [comment]
Was this fixed with the following commit?

https://github.com/eymengunay/php-passbook/commit/f18bb4a7fb1f71e3f0861aba1421434b0a353253
