### ISSUE TITLE
Relevance Information: Displaying Passes on the Lock Screen

### ISSUE THREAD

**Issue by sameg14** [eymengunay/php-passbook#36]
I need to be able to add relevant locations to the passbook file. How do you propose I go about doing this?
This is what the JSON will look like 
```json
{
    ...
    "description" : "Example pass showing relevance information",

    "locations" : [

        {"latitude" : 37.3229, "longitude" : -122.0323},

        {"latitude" : 37.3286, "longitude" : -122.0143},

        {

            "altitude" : 10.0,

            "latitude" : 37.331,

            "longitude" : -122.029,

            "relevantText" : "Store nearby on 3rd and Main."

        }

    ],

    "relevantDate" : "2014-12-05T09:00-08:00"

}
```

**Comment by sameg14** [comment]
Take a look at this URL for more details https://developer.apple.com/library/ios/documentation/UserExperience/Conceptual/PassKit_PG/Chapters/Creating.html#//apple_ref/doc/uid/TP40012195-CH4-SW53

**Comment by eymengunay** [comment]
@sameg14 You can use [Location](https://github.com/eymengunay/php-passbook/blob/master/src/Passbook/Pass/Location.php) to achieve that.

Also, take a look at the relative [test](https://github.com/eymengunay/php-passbook/blob/master/tests/Passbook/Tests/Pass/LocationTest.php) to see how to use it:

Here is a dummy example:

```php
use Passbook\Type\EventTicket;
use Passbook\Pass\Location;

// Create an event ticket
$pass = new EventTicket("1234567890", "The Beat Goes On");
$pass->setBackgroundColor('rgb(60, 65, 76)');
$pass->setLogoText('Apple Inc.');

// Create a new location
$location = new Location(55.6819, 12.5642);
$pass->addLocation($location);

// Create another location
$location = new Location(34.0478, -118.2434);
$pass->addLocation($location);
```

**Comment by sameg14** [comment]
Awesome, you rock. Thanks man

**Comment by eymengunay** [comment]
I'm glad I was able to help! :)
