### ISSUE TITLE
Apple Developer Program

### ISSUE THREAD

**Issue by eriktobben** [eymengunay/php-passbook#37]
Hi!

Do I need to enroll in the Apple Developer Program to be able to create Passbook / Wallet passes?

**Comment by eymengunay** [comment]
Hi @eriktobben ,

Yes, you will definitely need to create an apple ios developer account to start publishing passes. You can find more information here:

https://developer.apple.com/passbook/Getting_Started_with_Passbook.pdf

**Comment by eriktobben** [comment]
Okey, thanks! :-)
