### ISSUE TITLE
Problems with mkdir()

### ISSUE THREAD

**Issue by eriktobben** [eymengunay/php-passbook#38]
Hi!

I am getting the following error:

ErrorException in PassFactory.php line 159:
mkdir(): Permission denied

I have checked that the owner of the folder is the same as executes PHP.

How to fix this?

**Comment by eymengunay** [comment]
Hi @eriktobben,
The issue you are having is not related to php-passbook. It might be caused due to wrong permissions or something else similar. I'd suggest you to check folder permissions to see if it is writable.

**Comment by eriktobben** [comment]
Hi!

I just found the error. I am using Laravel, and I hadn't added the whole path to the folder.
