### ISSUE TITLE
backFields

### ISSUE THREAD

**Issue by eriktobben** [eymengunay/php-passbook#39]
Hi!

Is it possible to use backFields? (Add data to the back side of pass)

**Comment by eymengunay** [comment]
Yes, you can see it from here: https://github.com/eymengunay/php-passbook/blob/ccd757a9c0870237575ca01e73346446294eba4e/src/Passbook/Pass/Structure.php#L153

PS: There is also an api doc which may come handy: 
http://eymengunay.github.io/php-passbook/api/
