### ISSUE TITLE
Line break

### ISSUE THREAD

**Issue by eriktobben** [eymengunay/php-passbook#40]
I am having trouble adding a line break on the BackField. I have tried \r\n and \n but this is included in the pass as text. I saw in the Apple documentation that they were using \n. Do you handle that different?

**Comment by g-** [comment]
There are several ways to do this. I've done it using line breaks within the string as it doesn't require any conversion.

```php
        $fieldValue = 'First line

Second line';
```

If you are using \n in the string, make sure you are using double quotes. With single quotes it will display \n literally which sounds like it could be your problem.
