### ISSUE TITLE
how to generate 'mykey.key'

### ISSUE THREAD

**Issue by navi298** [eymengunay/php-passbook#41]
How to create the 'mykey.key'?

**Comment by g-** [comment]
Follow the instructions in the Readme.

The link to the Apple Developer documentation has changed. Try this one: https://developer.apple.com/library/ios/documentation/UserExperience/Conceptual/PassKit_PG/YourFirst.html#//apple_ref/doc/uid/TP40012195-CH2-SW27

**Comment by navi298** [comment]
Thanks.
