### ISSUE TITLE
no paired key file with iphone developer certificate.

### ISSUE THREAD

**Issue by navi298** [eymengunay/php-passbook#42]
I don't see any key which is paired with iphone developer certificate.
Can I get it from any other way?
Is that Pass type certificate or iphone developer certificate?

**Comment by g-** [comment]
It is a Pass Type ID certificate.

The Apple Developer has step-by-step instructions.

https://developer.apple.com/library/ios/documentation/UserExperience/Conceptual/PassKit_PG/YourFirst.html#//apple_ref/doc/uid/TP40012195-CH2-SW27
