### ISSUE TITLE
Help please

### ISSUE THREAD

**Issue by Yogg86** [eymengunay/php-passbook#44]
All works good , but i have 1 issue , when i creating new pkpass, my file have strange srtucture , pkpassname and path folders.
With this structure , mac can't open this passbook
Help me please.
Thanks.

**Comment by sameg14** [comment]
What is the JSON you are using to generate the pass? What does your client code look like?

**Comment by Yogg86** [comment]
I use type generic , i use laravel framework , and i think problem in paths, in $factory->setOutputPath($base_url. '/pass');
where my $base_url = ''E:\Server\OpenServer\domains\ysapplaravel.dev"

**Comment by sameg14** [comment]
Looks like your mixing slashes on windows use `DIRECTORY_SEPARATOR` instead

**Comment by Yogg86** [comment]
thanks ,problems was in windows:)

**Comment by sameg14** [comment]
Awesome! Glad you figured it out. Can you close the issue?

**Comment by Yogg86** [comment]
yeah , sure :+1:
