### ISSUE TITLE
Usage example

### ISSUE THREAD

**Issue by canfiax** [eymengunay/php-passbook#45]
Would be great with a usage example to create, say a Ticket. From generation to outputting to user.

**Comment by g-** [comment]
There is a usage example in the README.md file. What would you like added to this example?

**Comment by canfiax** [comment]
Thanks for quick reply. I think it's a bit confusing. Will the example in the readme output anything? Do I need to echo any values? A little description of what the code actually does would be nice :)

**Comment by g-** [comment]
Is this better? https://github.com/g-/php-passbook#usage-example

**Comment by canfiax** [comment]
I like! 

What is OUTPUT_PATH? Is this where the passbook file will be? Or is the passbook file outputted directly from the example code?

**Comment by g-** [comment]
Yes, that is where the file is saved. The output of the $factory->package($pass) call is a pkpass file which is saved in the file system in the path specified.

I must confess, I haven't tested these changes in the example code; if you can confirm that it works, I'll update the readme on the main project.

**Comment by canfiax** [comment]
OK, and then you redirect the visitor to that output_path, and they will be able to download it? Or even just stream the file to the browser?

I'll let you know when I have tested that it works.

**Comment by g-** [comment]
Yes, once the file is saved, you can do what you like with it.

Did the example work for you?
