### ISSUE TITLE
Slashing on Windows for Zip issue

### ISSUE THREAD

**Issue by vogtdominikgit** [eymengunay/php-passbook#47]
Hey, just wanted to let you know that i found an issue for windows. 

PassFactory seems to have a problem in the zip() function at Line 362 where the slashes for UNIX are brought in the right direction. But for Windows this causes an issue.

So i added $file = str_replace('\\', '/', $file); directly after this line, to solve this issue.

Im not sure how to add a pull request. So this is how im letting you know.

**Comment by g-** [comment]
I see your point. The documentation for realpath() says:

> On windows realpath() will change unix style paths to windows style.

I'd imagine the same normalisation as used above in the code would be required:

`$file = str_replace('\\', '/', $file);`

**Comment by vogtdominikgit** [comment]
I could solve it with. I am writing just now, because i have this issue again.

`$file = str_replace('\\', DIRECTORY_SEPARATOR, $file);`

Is my solution. Just use the PHP Constant for each '/' inside the zip function.

**Comment by g-** [comment]
Yes, it would definitely be better to use DIRECTORY_SEPARATOR rather than str_replace all over the place.

**Comment by g-** [comment]
Even better would be to use the getSubPathName() method of the RecursiveDirectoryIterator to avoid string manipulation to get the relative path. I've rewritten the method using this approach. Could you check that it works for you?
