### ISSUE TITLE
Image format

### ISSUE THREAD

**Issue by hpatoio** [eymengunay/php-passbook#48]
AFAIK only PNG images are allowed in pkpass files.

I was using this library and I tried to add JPG images but were not showed up. The library should throw an exception if non PNG image is added. Do you agree ? I've already a draft for this I can send a PR

**Comment by eymengunay** [comment]
Hi @hpatoio,

I'd prefer keeping image validation logic outside of this library as the validation process might become a little too complex. Do we just check the file extension, what happens if somehow the file extension is wrong etc.

However, I guess a simple extension check won't hurt anybody ;)

**Comment by g-** [comment]
I'd go for the simple file extension check. I definitely wouldn't try to validate the image itself.

I've started a PassValidator class to check for common (and frustrating) errors which cause the pass to just not work. This might be a good place for this kind of check.

**Comment by hpatoio** [comment]
@g- that's way I wanted to add some sort of validation. I wasted hours because I was adding JPG isntead of PNG. When you open a not valid pass file the iPhone doesn't show any error message. It simply doesn't load the pass (or part of it)

**Comment by hpatoio** [comment]
Thanks ! Let's tag a new minor release !
