### ISSUE TITLE
Cannot add pass to wallet

### ISSUE THREAD

**Issue by notihnio** [eymengunay/php-passbook#51]
Hi! thanks for the library! I face a small problem. when i create a pass i can open it from osx, android but when i try to download it from safari i cannot simple import it to ios(9) wallet. The ios promt opens and ask me to choose an app to open the file.

I have check the AppleWWDRCA.pem, i download the file from https connection... , i have try ios simulator is assertion failed: 15A278b 13E230: assertiond

Any idea?

**Comment by eymengunay** [comment]
Hi @notihnio,

I think the problem is the wrong content-type for the pass file. Make sure that you are serving the pass with `Content-Type: application/vnd.apple.pkpass` header. 

You can see a simple example here: https://github.com/eymengunay/php-passbook/blob/master/www/router.php

**Comment by notihnio** [comment]
Thanks my friend that was the problem. Solved!!
