### ISSUE TITLE
Problem with generated zip

### ISSUE THREAD

**Issue by memento86** [eymengunay/php-passbook#56]
HI!
The pkpass file doesn't work at iphone devices. When the file is downloaded by Safary, it is showed this error: "Safari cannot download this file". I am testing with simulator of xcode and show the next logs:

Jun 23 18:06:41 iMac MobileSafari[646]: BOM could not extract archive: Couldn't read PKZip signature
Jun 23 18:06:41 --- last message repeated 1 time ---
Jun 23 18:06:41 iMac MobileSafari[646]: PassBook Pass download failed: The pass cannot be read because it isn’t valid.

I have generated the p12 file like you say at https://github.com/eymengunay/php-passbook#p12-certificate.

Finally, I can install the pkpass at Android devices.

I hope that you can help me.

Thank you!

**Comment by g-** [comment]
That is a symptom of the pass not being signed correctly. Android does not validate the signature so will load the pass, but iPhone will only load passes that are correctly signed.

**Comment by memento86** [comment]
Hi!
Thanks for your answer. But I have done every step to create the certificates a lot of times and pkpass doesn´t work on iphone device. I don'´t know that try...

**Comment by memento86** [comment]
It works now :) I have generated the p12 certificate using other mac. You can close the issue.

Thank you!

**Comment by g-** [comment]
Glad you figured it out!
