### ISSUE TITLE
Support for 3x images

### ISSUE THREAD

**Issue by glennschmidt** [eymengunay/php-passbook#60]
Apple docs say that all PNG assets in a pass can now include 3x versions alongside the 2x.

It would be good if the library could support adding these assets to the pass (maybe replace `isRetina` in the `Image` class with a `density` property which equals 1, 2 or 3)

**Comment by eymengunay** [comment]
Hi @glennschmidt ,

I have just released v2.0.0. `setRetina` and `isRetina` methods are replaced with `setDensity` and `getDensity` respectively. Thank you for the suggestion!
