### ISSUE TITLE
need help 

### ISSUE THREAD

**Issue by fazala78** [eymengunay/php-passbook#62]
i m new in development 
i install passbook library in cakephp using composer 
i add the example code in passbook.php file in src/Passbook folder and include the file in my controller 

< ? p h p
require '../../autoload.php';
use Passbook\Pass\Field;
use Passbook\Pass\Image;
use  `#Passbook\PassFactory;`
use Passbook\Pass\Barcode;
use Passbook\Pass\Structure;
use Passbook\Type\EventTicket;

// Set these constants with your valuesâ€¨
define('P12_FILE', '/cer/HTViOSPassKitP12File.p12');
define('P12_PASSWORD', '123456789');
define('WWDR_FILE', '/cer/wdrc.pem');
define('PASS_TYPE_IDENTIFIER', 'pass.com.htvi.os');
define('TEAM_IDENTIFIER', '26V2Q4KMYM');
define('ORGANIZATION_NAME', 'NEWSPAPER AGENCY COMPANY LLC');
define('OUTPUT_PATH', '/cer/coupon');
define('ICON_FILE', '/cer/book.png'); 

here is the passbook.php code 
when i run the function it show 

**page isn’t working
HTTP ERROR 500**
please help me

**Comment by eymengunay** [comment]
hi @fazala78, can you give more details? are you receiving an error?

**Comment by fazala78** [comment]
it show http error 500

**Comment by Braunson** [comment]
@fazala78 Check your PHP's error_log for a detailed error.
