### ISSUE TITLE
Open Passbook on Android app

### ISSUE THREAD

**Issue by Piero87** [eymengunay/php-passbook#65]
Hi,
I can add the Passbook on iOS, but when I'm trying to add it on an Android App like Pass2U the Passbook is black I can see only the barcode, instead if I open it on another Android app like PassWallet give me an error that can't open it. There a fix? someone know this problem?

**Comment by eymengunay** [comment]
Hi @Piero87 ,
I have never tried applications like Pass2U so I'm not sure if there is a way to debug it but I can only suggest looking into that.

**Comment by Piero87** [comment]
Ok Thanks, any hint on how to make a debug for android?

**Comment by g-** [comment]
As a general debugging suggestion, try manually constructing a pass or making as simple a pass as possible that you know is valid and works. Then, add keys back in one by one until you find what is causing the problem. You may also want to check for known issues with the Android apps.
