### ISSUE TITLE
When add barcode, add also a "barcodes" in the json

### ISSUE THREAD

**Issue by Piero87** [eymengunay/php-passbook#66]
Hi,
when I add a barcode to the passbook, the json contains a "barcode" key and also a "barcodes" that is an array with the barcode, why?

**Comment by g-** [comment]
The barcode key has been replaced by barcodes.

> With the release of iOS 9, there are two ways to display a barcode:
> * The barcodes key (new and required for iOS 9 and later)
> * The barcode key (for iOS 8 and earlier)
> To support older versions of iOS, use both keys. The system automatically selects the barcodes array for iOS 9 and later and uses the barcode dictionary for iOS 8 and earlier.

https://developer.apple.com/library/content/documentation/UserExperience/Reference/PassKit_Bundle/Chapters/TopLevel.html#//apple_ref/doc/uid/TP40012026-CH2-SW5
