### ISSUE TITLE
remove from lockScreen using relevantDate

### ISSUE THREAD

**Issue by Piero87** [eymengunay/php-passbook#67]
Hi,
If I add a relevantDate for an event ticket, I can see it at the relevantDate in the lock screen, but remain there and doesn't go away, the only way to remove it from the lock screen is to remove the passbook from the Wallet or uncheck the lock screen option for that passbook. Anyone knows if there is an expiry date and remove it automatically?

**Comment by g-** [comment]
To the best of my knowledge, the system controls the behaviour of the relevantDate. Here's a similar question on Stackoverflow...

http://stackoverflow.com/questions/13597103/can-a-passbook-pass-be-relevant-for-multiple-days
