### ISSUE TITLE
Validation fails as soon as I specify a webserviceURL

### ISSUE THREAD

**Issue by timinho** [eymengunay/php-passbook#72]
Thanks a lot for making this library available. I am able to create passbooks but when Im trying to add them to my Wallet its not letting me. I've read online that they must be served over https which I've tried as well. 

Is a webserviceURL a requirement for adding a passbook to a wallet? As soon as I add `$pass->setWebServiceURL('https://test.com');` Im getting a `Failed to validate passbook` (without one of the error messages in the PassValidator.php being passed).

**Comment by eymengunay** [comment]
Hello @timinho ,

I'm sorry to hear that you are having problems but the webservice url is **not** required for adding a pass.

**Comment by razvanphp** [comment]
I'm using this feature without any problems, must be something with your Service API, maybe you need to implement some specific endpoints like:
```
POST v1/devices/<deviceLibraryIdentifier>/registrations/<passTypeIdentifier>/<serialNumber>
GET v1/devices/<deviceLibraryIdentifier>/registrations/<passTypeIdentifier>
DELETE v1/devices/<deviceLibraryIdentifier>/registrations/<passTypeIdentifier>/<serialNumber>
```
