### ISSUE TITLE
the grouping identity may only be used on boarding pass and event ticket types

### ISSUE THREAD

**Issue by rbaarsma** [eymengunay/php-passbook#77]
updating from `2.0.0` to `2.1.0` broke our code

When using another ticket type than boarding pass or event tickets, this exception is thrown:
"the grouping identity may only be used on boarding pass and event ticket types"

Looking in the code in https://github.com/eymengunay/php-passbook/blob/master/src/Passbook/PassValidator.php it seems the `validateGroupingIdentity()` is always called and simply validates if the pass type is `boardingPass` or `eventTicket`. All other types are simply invalid.. 

seems like a pretty serious bug to me, but easy to fix

**Comment by eymengunay** [comment]
Hello @rbaarsma,

Thank you for pointing this out. I don't know how it went unnoticed until now. It is now fixed in: a5b05f3ddedf20f41c5c7f5eda38ea362732190d

Here is also the new release containing this fix:
https://github.com/eymengunay/php-passbook/releases/tag/v2.1.1
