### ISSUE TITLE
sharingProhibited flag

### ISSUE THREAD

**Issue by koekaverna** [eymengunay/php-passbook#79]
Is it possible to set sharingProhibited = true?
This option disable sharing feature of the card.

**Comment by eymengunay** [comment]
Unfortunately I couldn't find any references to `sharingProhibited` key. The closest I got was this answer: https://stackoverflow.com/questions/42192152/is-there-any-way-to-disable-share-pass-button-from-wallet-pass-and-android-pay/48008507#48008507

The [reference document](https://developer.apple.com/library/content/documentation/UserExperience/Reference/PassKit_Bundle/Chapters/Introduction.html#//apple_ref/doc/uid/TP40012026-CH0-SW1) still doesn't mention much about this flag so I'd rather wait a little more. Although if you are able to test feature this please feel free to send in a pull request.

**Comment by koekaverna** [comment]
I make pull request https://github.com/eymengunay/php-passbook/compare/master...7a198d68319c4cc26a2bd0433407a882aeac5056

Tested on iOS 11 and it work.
Not working on android Wallet Passes

**Comment by eymengunay** [comment]
Thank you! Looks good to me. 

Do you want to go ahead and send the pr?
