### ISSUE TITLE
error can open pass.pkpass

### ISSUE THREAD

**Issue by danirub** [eymengunay/php-passbook#82]
Hi I get an error. "the pass 'pass.pkpass'  could not be opened .
<img width="420" alt="Screen Shot 2019-09-03 at 21 34 47" src="https://user-images.githubusercontent.com/4972325/64199296-ae84da00-ce92-11e9-8255-b6a2721cbd9d.png">

**Comment by consult-info** [comment]
and i. help!

**Comment by Sophikitis** [comment]
If you have a Mac computer, you can open the console app, in tab error you can see errors of type pass viewer. 
You will have the error detail.
Most of the time is field required missing.

**Comment by razvanphp** [comment]
Please paste your console messages if you still have problems related to generating a valid pass with this library.

I would then add extra validation & unit tests for this case.

Thank you!
R
