### ISSUE TITLE
Align text into passbook

### ISSUE THREAD

**Issue by sbellver** [eymengunay/php-passbook#83]
Is any way to center the text?

I try into logoText and Secondary Field with no success

**Comment by sbellver** [comment]
I use as:

`$secondary = new Field('nombre', 'TEXTO A MOSTRAR' );
$secondary->setTextAlignment('ALIGN_CENTER');
$secondary->setLabel('Nombre');
$structure->addSecondaryField($secondary);`

But then the passbook have an error and cannot open it. If i comment 

`$secondary->setTextAlignment('ALIGN_CENTER');`

Passbook is generated/opened without problems

**Comment by razvanphp** [comment]
The values you have to pass are different, see here: https://github.com/eymengunay/php-passbook/blob/master/src/Passbook/Pass/Field.php#L23

In your case you are not using the constants, try this:
```
$secondary->setTextAlignment(\Passbook\Pass\Field::ALIGN_CENTER);

**Comment by sbellver** [comment]
Your right, thx
