### ISSUE TITLE
Composer installation problem…

### ISSUE THREAD

**Issue by jadecrea** [eymengunay/php-passbook#88]
After putting ""eo/passbook": "dev-master" in the require section of my composer.json file and running "composer update" I have this message : 
Problem 1
    - Root composer.json requires eo/passbook dev-master -> satisfiable by eo/passbook[dev-master].
    - eo/passbook dev-master requires php >=7.4 -> your php version (7.3.17) does not satisfy that requirement.
    
The documentation indicates that the minimum required version for PHP is 5.4. 
This message tell me that I need at least PHP version 7.4 !
However, my production server is in v 7.3, so this is a problem. 
 
What did I do wrong?

**Comment by eymengunay** [comment]
Hello @jadecrea ,

The current latest release v3.0 indeed requires PHP >= 7.4 and it was introduced first by 6df4877d249ff51786dd0ad439c5f3ae9ec2deb1.

I'd suggest you to rollback to v2.1.0 which supports PHP 5.x.

**Comment by razvanphp** [comment]
[README.md](https://github.com/eymengunay/php-passbook/blob/master/README.md#version-300) now includes this requirement.
