### ISSUE TITLE
PHP 8.1 deprecation warnings

### ISSUE THREAD

**Issue by cfreear** [eymengunay/php-passbook#91]
PHP Deprecated:  Return type of Passbook\Pass\Image::getExtension() should either be compatible with SplFileInfo::getExtension(): string, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice.

**Comment by eymengunay** [comment]
Dear @cfreear 

Thank you for bringing this to attention. I haven't been doing any active maintenance of this repo since a while except for reviewing and accepting submitted pull requests.

It'll be much appreciated if you can submit a PR that fixes it.

Thank you.

**Comment by razvanphp** [comment]
Fixed in PR #99 and released as [v3.1.2](https://github.com/eymengunay/php-passbook/releases/tag/v3.1.2)

Duplicate of #97
