### ISSUE TITLE
Should check isOverwrite() on prepareLocalizations() as well

### ISSUE THREAD

**Issue by ioliva** [eymengunay/php-passbook#92]
This mkdir() causes an error even if isOverwrite() returns true: https://github.com/eymengunay/php-passbook/blob/0a7949712e47ccd835d6d21211b3a36fbdda07e0/src/Passbook/PassFactory.php#L510

That's because isOverwrite() is checked only for the main pass directory, but not for the localizations subdirs. If isOverwrite() is true, the previous localization subdirs should be deleted as well, just before preparing the localizations again.

**Comment by eymengunay** [comment]
Hi @ioliva,

Thank you for pointing this out! Unfortunately I do not actively contribute to this repo however any bugfix/new feature PR's are always welcome.
